### ISSUE TITLE
Any way to bypass the limitation if you don't have the game purchased?

### ISSUE THREAD

**Issue by DimaSheiko** [BerdyAlexei/SCMD-Workshop-Downloader-2#1]
Hello, I would like to download mods from steam workshop, but I don't have the game purchased and the program shows me the error. Is there any way to bypass this limitation?

**Comment by BerdyAlexei** [comment]
> 

Unfortunately not "legally" and therefore not with SteamCMD, however there are pages that collect some mods of non-listed applications, although of course these items may not be updated, they usually work quite well.

**Comment by DimaSheiko** [comment]
Thank you!
By the way, I've been looking for something like this for a long time, too bad I got it when SteamCMD already imposed the limitation. Great work.
