### ISSUE TITLE
trying to change location for downloads?

### ISSUE THREAD

**Issue by dinoking27** [BerdyAlexei/SCMD-Workshop-Downloader-2#12]
trying to change the folder on where to put the downloads and Idk how to change it too because it says apps folder and change folder so where do i put them at?

**Comment by BerdyAlexei** [comment]
That problem has just been fixed in version `1.1.1-beta` of _SCMD Workshop Downloader 2_, give it a try.
I'm sorry I didn't reply to you earlier. 😅
