### ISSUE TITLE
Custom download location breaks 

### ISSUE THREAD

**Issue by jimbot03** [BerdyAlexei/SCMD-Workshop-Downloader-2#13]
When you're using paths with spaces in the name for custom download locations it drops everything after the first space 

Normally in steam CMD adding "" around the location fixes this however the script doesn't do that by default and the app setting doesn't allow quotations as a valid input

**Comment by BerdyAlexei** [comment]
Thanks for letting me know about it and also giving me a solution, friend. You're great. I just released the application with that bug fixed. Thanks, again.
