### ISSUE TITLE
2694448564 still can't download

### ISSUE THREAD

**Issue by unpack2L** [BerdyAlexei/SCMD-Workshop-Downloader-2#2]
https://steamcommunity.com/sharedfiles/filedetails/?id=2694448564 still can't download, both SteamCMD SCMD Workshop Downloader 2, Can you download it for me? thank you

**Comment by BerdyAlexei** [comment]
Of course, I can send it to you through the app's Discord:
https://github.com/BerdyAlexei/SCMD-Workshop-Downloader-2#social-media

By the way, could you tell me why the download doesn't work? _(If you get an error or something like that)_
