### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AA-1385** [BerdyAlexei/SCMD-Workshop-Downloader-2#3]
i started it in windows 7 gets an error

no error massages generated.
formatmessagew: the parameter is incorrect

**Comment by BerdyAlexei** [comment]
The app only works on Windows 10-64 bits and up.
I forgot to write it in the readme, sorry.

**Comment by BerdyAlexei** [comment]
The app only works on Windows 10-64 bits and up as stated in the readme:
https://github.com/BerdyAlexei/SCMD-Workshop-Downloader-2#can-my-computer-run-scmd-workshop-downloader-2
