### ISSUE TITLE
getting time out trying to download an addon from a supported game

### ISSUE THREAD

**Issue by imkedux** [BerdyAlexei/SCMD-Workshop-Downloader-2#4]
(the games its bo3 btw)theres anything i can do? exact error:
Waiting for client config...OK
Waiting for user info...OK
Downloading item 2451589519 ...ERROR! Timeout downloading item 2451589519

**Comment by BerdyAlexei** [comment]
_Workshop files_ larger than _250 MB_ require you to **activate the _Big Sized Items Mode (BSIM)_** in the options tab of the application _(Button with a gear on the bottom left)_.

Activate the option and start the download, it _should_ be enough to fix the problem.
I'll leave the _issue open so you can let me know if everything worked_ for you.

**Comment by imkedux** [comment]
that did work thanks
